In [1]:
import os
import itertools
import xlsxwriter

import numpy as np
import pandas as pd
from scipy.optimize import minimize
from sklearn.model_selection import TimeSeriesSplit
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_validate
import statsmodels.api as sm 
import matplotlib.pyplot as plt

import DataPreparation as dpr
import Models
import benchmarks as bench
from MyEstimators import CLS_Estimator

<Figure size 720x360 with 0 Axes>

In [5]:
import os
import itertools

import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
import statsmodels.api as sm

import Models

def xy_generator(parameters, sample_size, function, **options):
    # error generation
    v1, v2 = np.random.standard_normal(sample_size + 100), np.random.standard_normal(sample_size + 100)

    x = v1+1
    y = v2+100

    return x, y

opt = {'stationary' : True,
       'error_type': 'standard',
       'constraint' : True}

xy_generator(parameters=1, sample_size=1000, function='a', options = opt)

(array([ 1.93691941, -0.10235938,  0.74940663, ...,  1.07449755,
         0.90605023,  1.81707733]),
 array([100.55350683,  99.64633967,  98.28067447, ...,  99.69380946,
        100.5807049 ,  99.92890338]))

In [7]:
data, y, y_lag, x, z = xy_generator(parameters=1, sample_size=1000, function='a', options = opt)

ValueError: not enough values to unpack (expected 5, got 2)

In [8]:
xy_generator(parameters=1, sample_size=1000, function='a', options = opt)

(array([0.41601044, 0.3125801 , 0.75954434, ..., 0.68162168, 1.87484269,
        1.04481202]),
 array([100.42217689, 101.05567719,  99.67021513, ...,  99.11390476,
         99.43904796,  98.92020121]))